

@baseUrl = http://localhost:3333


# @name getHealth
GET {{baseUrl}}/health

###

#Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "Uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# @name getRoomQuestion
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# @name createQuestion
POST {{baseUrl}}/rooms/ebc3c0bc-0adc-4226-8f3e-9c299b82a076/questions
Content-Type: application/json

{
    "question": "O que é divisão celular?"
}



